### ISSUE TITLE
rate limitations

### ISSUE THREAD

**Issue by fl0wo** [d60/twikit#100]
Any hint to avoid account bans? What are the request limits?
(just for educational purposes obv, I would never)

**Comment by d60** [comment]
@fl0wo
https://github.com/d60/twikit/blob/main/ToProtectYourAccount.md

**Comment by fl0wo** [comment]
Awesome job man.

Are those limits HTTP calls or actual number of records returned for example:

`get_user_tweets[tweet_type="Replies"] 50 
`

Means 50 tweets fetched every 15 min, or 50 get_user_tweet calls every 15 min?

https://github.com/d60/twikit/blob/main/ratelimits.md

**Comment by sargon17** [comment]
any update here?

**Comment by fl0wo** [comment]
I got hammer banned from X twice kek, (just for educational purposes obv, I would never)

Seems like even if you stay below the rate limits, still your account can get suspended as there's a ML behind that knows if a behaviour is human-like or not.

Even trying to bypass it as much as possible with random delays and GPT-powered messages, still get suspended.

Gotta try reducing 100x the comments frequency to: max 6 a day and see what happens

**Comment by sargon17** [comment]
Ok, thank you.

How about simple tweets fetching rates?

**Comment by fl0wo** [comment]
> Ok, thank you.
> 
> How about simple tweets fetching rates?

I don't know, I have to do more testing in the next days and let you know.

**Comment by TurbatBay** [comment]
> > Ok, thank you.
> > How about simple tweets fetching rates?
> 
> I don't know, I have to do more testing in the next days and let you know.

What happened any updates?

**Comment by noodleman420** [comment]
@fl0wo were you able to test what is a good rate?

**Comment by Carter4242** [comment]
I'm wondering the same thing, it might be they don't like you using new accounts as well...

**Comment by noodleman420** [comment]
> I'm wondering the same thing, it might be they don't like you using new accounts as well...

Don't think so, I used a very old account and it still got suspended. No difference in account age

**Comment by Carter4242** [comment]
@noodleman420 Yeah no idea, I wasn't logging in a bunch, just fetching new tweets every so often, by all accounts this shouldn't have triggered anything, I'm sure it was a very suspicious account on their end though (VPN, proton email address).

**Comment by ObiAU** [comment]
> I got hammer banned from X twice kek, (just for educational purposes obv, I would never)
> 
> Seems like even if you stay below the rate limits, still your account can get suspended as there's a ML behind that knows if a behaviour is human-like or not.
> 
> Even trying to bypass it as much as possible with random delays and GPT-powered messages, still get suspended.
> 
> Gotta try reducing 100x the comments frequency to: max 6 a day and see what happens

were you able to get it workign?
