### ISSUE TITLE
Auto Phone Number

### ISSUE THREAD

**Issue by DvScripts** [d60/twikit#104]
Hey
Don't You plan to add optional adding phone number?

so if this appear

`Verify your identity by entering the phone number associated with your X account.	`

it will auto fill the phone number? would be easier instead putting phone numbers manually now

**Comment by fishfree** [comment]
I still got this problem as below:

![Image](https://github.com/user-attachments/assets/49f1f311-1e26-4178-8b8d-6229e3cd345d)

How to solve it, pls?
