### ISSUE TITLE
status: 401, message: "{"errors":[{"message":"Could not authenticate you","code":32}]}

### ISSUE THREAD

**Issue by sky6861** [d60/twikit#108]
How should I handle this error?
I have logged in using cookies, and I have not exceeded the rate limit.
I search approximately every 23 seconds, and I see the rate limit is 50 requests every 15 minutes. Could you please advise me on how to resolve this error and avoid getting my account locked?

**Comment by PrinceFPF** [comment]
这个报错以及封禁机制跟本项目的开发者没关系，这与tweet官方的检测机制相关，这跟你所使用的IP、登录tweet的频次、发布推文的频率、发布推文的内容等都有关系，tweet官网会综合判定你是不是机器人或者发布的内容触犯了他们的封禁规则。
