### ISSUE TITLE
have an API to get comments?

### ISSUE THREAD

**Issue by Rgwww** [d60/twikit#115]
I'm not sure if there is an api to get comments on posts sent by bloggers I follow. I see TWEET_DETAIL and use client.get_tweet_by_id("xxxxx") but I can't get comments, so I don't know what to do

**Comment by d60** [comment]
@Rgwww 
You can retrieve comments on a tweet using `Tweet.replies`. If you need more comments you can get them with `replies.next`.
```python
tweet = client.get_tweet_by_id('xxxxx')
replies = tweet.replies
more_replies = replies.next()
```
