### ISSUE TITLE
Tweet Full Text issue

### ISSUE THREAD

**Issue by ZeeshanGeoPk** [d60/twikit#116]
Hello! 
There is an issue with the tweet.text and tweet.full_text, i tried both of them. I am unable to retrieve full tweet text. The code i am using is as follows:

    tweets = client.get_user_tweets("939058273487003648", 'Tweets')
    for tweet in tweets:
      print(tweet.full_text)

Also there is issue with "count" variable, it's default value is 20, and i am unable to change it. I mean, if i set the value "count=5", it still retrieves 20 tweets instead of 5.

Please fix this issue

**Comment by d60** [comment]
@ZeeshanGeoPk 
Maybe you are not getting the full text of the retweet.
Use tweet.retweeted_tweet.full_text to get the full text of a retweeted tweet
```python
tweets = client.get_user_tweets("939058273487003648", 'Tweets')
for tweet in tweets:
    if tweet.retweeted_tweet:
        print(tweet.retweeted_tweet.full_text)
    else:
        print(tweet.full_text)

```

**Comment by ZeeshanGeoPk** [comment]
Thank you so much. 
But what about the count variable? 
Whatever value of count I set, it always fetches 20 tweets
