### ISSUE TITLE
Rate Limit Issue with get_tweet_by_id “twikit.errors.TooManyRequests: status: 429”

### ISSUE THREAD

**Issue by TimoMe** [d60/twikit#119]
When I use this method to get tweets by tweetid, I quickly reach the retrieval limit. However, we have a 6-second sleep before using **get_tweet_by_id** each time. Has the retrieval limit been updated? The number of retrievals has decreased significantly.

**Comment by Thytu** [comment]
> When I use this method to get tweets by tweetid, I quickly reach the retrieval limit. However, we have a 6-second sleep before using **get_tweet_by_id** each time. Has the retrieval limit been updated? The number of retrievals has decreased significantly.

Hey, from what I know, each basic X account is limited to see 600 tweets a day (6k/day for verified account). That's probably the source of your error.
