### ISSUE TITLE
is it possible to write to group dialogs and receive a message from them?

### ISSUE THREAD

**Issue by antizhyk** [d60/twikit#12]
Good afternoon, first of all I am very grateful for your app it is a Herculean effort and you are a hero for me. 

I have such a question, is it possible to receive messages and write in group chats? If not, can you suggest the direction where to dig I will then try to add this functionality and send to the pool requester.

**Comment by antizhyk** [comment]
It turns out it was just a matter of changing the id. Chats with a user have the structure xxxxxxxxxxxx-xxxxxxxxxxx and group chats just xxxxxxxxxxxxxxx tomorrow I will write a description and send it to the pool request.

``` py
    def get_gm_history(self, gm_id: str, max_id: str | None = None) -> Result[Message]:
        params = {
            'context': 'FETCH_DM_CONVERSATION_HISTORY'
        }
        if max_id is not None:
            params['max_id'] = max_id

        response = self.http.get(
            Endpoint.CONVERSASION.format(gm_id),
            params=params,
            headers=self._base_headers
        ).json()

        status = response['conversation_timeline']['status']
        if status == 'AT_END':
            # If there are no more messages, an empty result list is returned.
            return Result([])

        items = response['conversation_timeline']['entries']
        messages = []
        for item in items:
            message_info = item['message']['message_data']
            messages.append(Message(
                self,
                message_info,
                message_info['sender_id'],
                message_info['recipient_id']
            ))
        return Result(
            messages,
            lambda: self.get_dm_history(gm_id, messages[-1].id)
        )
        ```

**Comment by d60** [comment]
@antizhyk 

Thank you. I believe adding the 'is_group' argument to the 'get_dm_history' method would make implementing group chat functionality easy.

Best regards.

**Comment by antizhyk** [comment]
Yeah, that's probably best. I also found that the data that comes when requesting messages from group chats does not have the **recipient_id** field, which is not necessary when initializing the Message class, so I think it's worth making it optional.

```py
        for item in items:
            message_info = item['message']['message_data']
            print(message_info)
            messages.append(Message(
                self,
                message_info,
                message_info['sender_id'],
                message_info['recipient_id']
            ))
```

I'm going to go try this option but thought I'd post my action to see if anyone comes up with something better.

**Comment by d60** [comment]
Yes indeed, I would make the recipient_id parameter optional.

**Comment by d60** [comment]
@antizhyk 
Added functionality related to group DM.
https://github.com/d60/twikit/issues/15
