### ISSUE TITLE
Tweets not showing full text

### ISSUE THREAD

**Issue by alvwin** [d60/twikit#124]
Neither tweet.text nor tweet.full_text are displaying the tweet's entire text.

For example this tweet:
![grafik](https://github.com/d60/twikit/assets/93882810/09b5bdaf-0203-4b09-ba62-6dcf630e94f1)

is displayed as 
RT @ThomasOrTK: Google Cloud’s new partnership with Oracle provides a path for the world’s largest enterprises to use next generation cloud…

or this tweet
![grafik](https://github.com/d60/twikit/assets/93882810/cf0ac644-c8f0-426a-b4b0-ecbe159147cc)
RT @OfficialLoganK: Good news for @Google Developers:

- Gemini 1.5 Flash and 1.5 Pro are now GA
- Gemini 1.5 Flash now has a 1,000 RPM lim…

it appears to be only retweets. Can i somehow get the full text of a retweet?

**Comment by d60** [comment]
@alvwin 
To get the full text of a retweeted tweet:
```python
tweet.retweeted_tweet.full_text
```

**Comment by justin-dx** [comment]
I'm seeing that both `full_text` and `text` both return the same value
<img width="1189" alt="d60" src="https://github.com/user-attachments/assets/b1a892dc-a7bb-4c20-bad0-a2a74c6b067b">
