### ISSUE TITLE
Tweets by location

### ISSUE THREAD

**Issue by Massuk** [d60/twikit#126]
Hello, is there a way to obtain the coordinates of a tweet using id?
I have read the documentation but the geo place function is to generate a place using other parameters

**Comment by d60** [comment]
Added Tweet.place in V2.0.1.

**Comment by lgjluis** [comment]
Hello, can you give an example of the code to obtain the tweet.place? I was doing some tests but it gives me an error: AttributeError: 'Tweet' object has no attribute 'place'. 

My code:

tweets = client.get_user_tweets(user.id, 'Tweets')

for tweet in tweets:
    print(tweet.id) #print ok
    print(tweet.user.screen_name) #print ok
    print(tweet.text) # print ok
    print(tweet.place) # print error

**Comment by d60** [comment]
@lgjluis 
Hello.
`tweet.place` was added in version 2.0.1.  You're likely using an older version. Try upgrading twikit.  Also `tweet.place` returns a `Place` object if the author has location enabled, otherwise it returns `None`.

**Comment by lgjluis** [comment]
I installed it today. I have version 2.0.2 and I still get that error.

**Comment by AritzUMA** [comment]
I am using this code and works perfectly. Even if my tweets place are almost None.

`                    # Example: Searching for tweets containing the current word
                    user = await client.search_tweet('{word} lang:es', 'Latest')
                    tweets = user
                    
                    while len(accumulated_tweets) < 100:
                        for tweet in tweets:
                            print(
                                f'text: {tweet.text[:10]}...',
                                f'created at: {tweet.created_at}',
                                f'place: : {tweet.place}'
                            )
                            accumulated_tweets.append(tweet)  # Append each tweet to accumulated_tweets list
                        for _ in tqdm(range(25), desc="Progress", unit="s"):
                            time.sleep(1)
                        tweets = await tweets.next()
                        if len(tweets) == 0:
                            break`

**Comment by Massuk** [comment]
I made this structure:

```
def place_to_dict(place):
    if place is None:
        return None

    # Obtener bounding box coordinates
    bounding_box = place.bounding_box.get("coordinates", None)

    # Calcular centroide si hay bounding box
    if bounding_box:
        centroid = calculate_centroid(bounding_box[0])
    else:
        centroid = None

    return {
        'id': place.id,
        'name': place.name,
        'full_name': place.full_name,
        'country': place.country,
        'place_type': place.place_type,
        'bounding_box': bounding_box,
        'centroid': centroid,
    }
    
async def fetch_tweets(keywords):
    search_result = await client.search_tweet('keywords here', 'Latest')
    for tweet in search_result:
        tweet_place = place_to_dict(tweet.place)

        tweets = {
            'Keywords': combined_keywords,
            'Tweet ID': tweet.id,
            'Tweet User ID': tweet.user.id,
            'Tweet User name': tweet.user.name,
            'Tweet Text': tweet.full_text,
            'Tweet In Reply to': tweet.in_reply_to,
            'Tweet Hashtags': tweet.hashtags,
            'Tweet Place': tweet_place['name'] if tweet_place else None,
            'Tweet Place Type': tweet_place['place_type'] if tweet_place else None,
            'Tweet Place Country': tweet_place['country'] if tweet_place else None,
        }
        tweets_list.append(tweets)

```

**Comment by lgjluis** [comment]
I'm trying with this simple code but I get the same error. I chage my version to 2.0.1. Please, can you send me a basic demo like this?

`from twikit import Client, Tweet


USERNAME = 'user'
EMAIL = 'mail@mail.com'
PASSWORD = 'pass'

client = Client('es-PE')

client.login(
    auth_info_1=USERNAME,
    auth_info_2=EMAIL,
    password=PASSWORD
)

result = client.search_tweet('UCV', 'Latest')

for tweet in result:
    print(tweet.id)
    print(tweet.user.screen_name)
    print(tweet.place)`

**Comment by Massuk** [comment]
Te adjunto un ejemplo básico, recuerda que debes usar las funciones asincrónicas según lo que indica el autor de la librería.

```
from twikit import Client
import asyncio

USERNAME = 'user'
EMAIL = 'mail@mail.com'
PASSWORD = 'pass'

client = Client('es-PE')

client.login(auth_info_1=USERNAME,auth_info_2=EMAIL,password=PASSWORD)

# Define una lista para que almacenes los tweets
lista_tweets = []

# Extrae informacion de la propiedad Place
def extraer_datos_place(place):
    if place is None:
        return None
    return {
        'id': place.id,
        'name': place.name,
        'full_name': place.full_name,
        'country': place.country,
        'place_type': place.place_type,
        'bounding_box': place.bounding_box,
        'centroid': place.centroid,
    }

#Buscar Tweets
async def buscar_tweets():
    result = await client.search_tweet('UCV', 'Latest')
    for tweet in result:
        tweet_place = extraer_datos_place(tweet.place)
        tweet_centroid = tweet_place['centroid'] if tweet_place else None
        tweets = {
            'ID del tweet': tweet.id,
            'ID del usuario': tweet.user.id,
            'Nombre de usuario': tweet.user.name,
            'Tweet': tweet.full_text,
            'Tweet Hashtags': tweet.hashtags,
            'Tweet Place': tweet_place['name'] if tweet_place else None,
            'Tweet Place Type': tweet_place['place_type'] if tweet_place else None,
            'Tweet Place Country': tweet_place['country'] if tweet_place else None,
            'Tweet Coordinates': tweet_centroid,
        }
        lista_tweets.append(tweets)
    print(lista_tweets)

asyncio.run(buscar_tweets())
```
