### ISSUE TITLE
Auth with 2FA

### ISSUE THREAD

**Issue by milkliker** [d60/twikit#128]
Hi, my accounts uses 2FA, so is that possible to login?
like use cookie or token instead of username/password.

**Comment by d60** [comment]
@milkliker 

You can log in by passing the TOTP secret key to the login function:

```python
client.login(
    auth_info_1='...',
    auth_info_2='...',
    password='...',
    totp_secret='your-secret-key'
)
```
Alternatively, you can log in by setting cookies directly in the client:

```python
cookies = {
    ...
}
client.set_cookies(cookies)
```

**Comment by milkliker** [comment]
@d60  Cool! I'm checking it out. Thanks!
