### ISSUE TITLE
How to fetch all tweets posted by a person? 

### ISSUE THREAD

**Issue by Victorvv-1024** [d60/twikit#131]
Hi, I do realise there is a rate limit for this service. So implemented a way to avoid reaching this limit, however, it keeps giving me repeated chunks of tweets for some reasons. 

We are trying to do a project and looking forward to publish a paper which would use Tweets data, if you can help us to resolve this issue, we are going to cite you.

Our code looks like this, if someone can help us, feel free to raise your point!

import time
from twikit import Client, Tweet
from typing import List

# Rate limit details
RATE_LIMIT = 50  # For tweets and replies
RESET_INTERVAL = 15 * 60  # 15 minutes in seconds
# User detail
USER_ID = user.id
TOTAL_TWEETS = user.statuses_count

def get_all_tweets(user_id: str) -> List[Tweet]:
    all_tweets = []
    tweet_types = ['Tweets', 'Replies']
    
    for tweet_type in tweet_types:
        tweets = []
        user_tweets = client.get_user_tweets(user_id, tweet_type, count=50)
        tweets.extend(user_tweets)
        
        while len(tweets) < TOTAL_TWEETS:
            # Check if we've hit the rate limit
            if len(tweets) % RATE_LIMIT == 0 and len(tweets) > 0:
                print(f"Reached rate limit. Waiting for {RESET_INTERVAL} seconds.")
                time.sleep(RESET_INTERVAL)
            
            more_tweets = user_tweets.next()
            if not more_tweets:
                break
            tweets.extend(more_tweets)
        
        all_tweets.extend(tweets)
    
    return all_tweets
    
all_tweets = get_all_tweets(USER_ID)
tweets_to_store = []
for tweet in all_tweets:
    tweets_to_store.append({
        'created_at': tweet.created_at,
        'favorite_count': tweet.favorite_count,
        'full_text': tweet.full_text,

**Comment by Neetpone** [comment]
I was having this same issue, and I discovered the fix:

You need to call next() on the new object each time; eg

Correct code:
```python
tweets = await client.get_user_tweets(user_id, tab)
# do something with Tweets

while tweets := await tweets.next(): # This reassigns `tweets` to be the next Tweets each time.
    # do something with additional Tweets
```

INCORRECT code:
```python
first_tweets = await client.get_user_tweets(user_id, tab)
# do something with Tweets

while more_tweets := await first_tweets.next(): # This is wrong! Keeps using the same cursor instead of the new one.
    # do something with additional Tweets
```
