### ISSUE TITLE
Breaking ratelimits.

### ISSUE THREAD

**Issue by ugsystem** [d60/twikit#135]
I thought of breaking ratelimits (specifically user tweets retrieval) by using the cursor value that's been generated with another user's session. Is this possible? If yes, I should be able to retrieve thousands of items without worrying about ratelimits.
I am yet to decipher how the cursor value works. It seems to vary every request.
I own hundreds of fake accounts and use capsolver.

**Comment by wslyyy** [comment]
> It turns out that this is possible. I was successful at retrieving ~8k tweets in 5 minutes by load-balancing across ~60 users at request rate way higher than in the case with a single user.
> 
> Also I will mention that huge tweets retrieval with a single user always led to account suspension in my case, but not with multiple users.


Can you share the code for your implementation?

**Comment by EyalShechtman** [comment]
commenting here to ask again!

**Comment by MarwanMansour** [comment]
Hey @ugsystem, sounds brilliant! Could you possibly share the implementation of sharing a search_tweets job between multiple accounts? I have a few questions about this method:

- How is the cursor shared between different user sessions?
- I'm still yet to fully understand the structure of the cursor as well, could you possibly share your insights on that?
- Does each independent user respect the rate limits individually while sharing the cursor data to avoid overlapping tweets retrieved?

Thanks a lot in advance!

**Comment by FelixSBuehrm** [comment]
Any update on this?
