### ISSUE TITLE
`UserTweets` has a hard limit.

### ISSUE THREAD

**Issue by ugsystem** [d60/twikit#136]
It seems that the endpoint `UserTweets` has a hard limit to how many tweets can be retrieved (up to about 700 tweets?). This behavior is the same with browsers. I'm logged in in both cases.
I plan to retrieve all tweets of a user (realistically up to about 10k tweets) and I'm unable to do so.

Any workaround?

The other endpoint `SearchTimeline` seems to work worse, as it won't retrieve any more than about 20- tweets.

**Comment by ws2bhhh** [comment]
Hi, I'm having a similar problem to yours, will this program solve my problem?
I need to retrieve all the replies under a certain tweet (about 600~), but previous attempts using the web app showed that my twitter account (or something else) prevented me from getting all the replies directly through the tweet page (only grabbing about 100~), and even fewer than 20 replies through the advanced search.

> > The other endpoint SearchTimeline seems to work worse, as it won't retrieve any more than about 20- tweets.
> 
> This was not true in general, but for some users. I was successful at retrieving about 2400 tweets.

Hi, I'm having a similar problem to yours, will this program solve my problem? Maybe I need more twitter account?
I need to retrieve all the replies under a certain tweet (about 600~), but previous attempts using the web app showed that my twitter account (or something else) prevented me from getting all the replies directly through the tweet page (only grabbing about 100~), and even fewer than 20 replies through the advanced search.
