### ISSUE TITLE
How to access my own tweets with authentication information to change the view count value.

### ISSUE THREAD

**Issue by PrinceFPF** [d60/twikit#145]
After creating a tweet, it shows None when i get the view_count. It's not what I want to see.
How to access my own tweets with authentication information to change the view_count value.
```python
res = await client.create_tweet(tweet_text)
tweet_id = res.id
tweet_obj = await client.get_tweet_by_id(tweet_id)
print(tweet_obj.view_count)


# result
None
```

**Comment by d60** [comment]
@PrinceFPF 
If view_count is none, it means that there were no views.

**Comment by PrinceFPF** [comment]
收到
