### ISSUE TITLE
unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by IK-O** [d60/twikit#146]
When I import twikit, it throws exceptiion bellow.

unsupported operand type(s) for |: 'type' and 'type'

Python version 3.9

OS Windows 11

IDE Visual Studio 2022

How can I fix this exception?

**Comment by DoggySazHi** [comment]
Try updating your Python version to 3.10 or later - Python 3.9 doesn't support PEP-604 to annotate union types, which is used by Twikit.

**Comment by IK-O** [comment]
It works. thank you.
