### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by Saul-Github** [d60/twikit#151]
# Initialize client
client = Client('en-US')

# Login to the service with provided user credentials
client.login(
    auth_info_1=USERNAME ,
    auth_info_2=EMAIL,
    password=PASSWORD
)

when trying to login, i got <coroutine object Client.login at 0x787e9e31d690>

**Comment by d60** [comment]
@Saul-Github 
The synchronous version has been deprecated since v2.0.0. 
https://github.com/d60/twikit/issues/152

**Comment by Saul-Github** [comment]
Thank you
