### ISSUE TITLE
The synchronous version has been deprecated since v2.0.0.

### ISSUE THREAD

**Issue by d60** [d60/twikit#152]
> [!IMPORTANT]
> With the release of version 2.0.0 on July 11, there have been some specification changes, including the discontinuation of the synchronous version. Existing code will no longer work with v2.0.0 or later, so please refer to the [documentation](https://twikit.readthedocs.io/en/latest/twikit.html) or the code in the [examples folder](https://github.com/d60/twikit/tree/main/examples) for adjustments.

https://github.com/d60/twikit/releases/tag/version2.0.0

**Comment by petraxeman** [comment]
Given the imminent release of Python 3.14 with a sufficiently optimized GIL-free interpreter build, wouldn't it make sense to reinstate support for the synchronous version?

The synchronous variant would allow the library to be used safely with the Free Threaded build (albeit with some overhead), as I assume that developing the library with full thread-safe Free Threading support is too costly for you.
