### ISSUE TITLE
Your account is suspended and is not permitted to access this feature.

### ISSUE THREAD

**Issue by fanvcz934n** [d60/twikit#156]
Your account is suspended and is not permitted to access this feature.
How to avoid this？

**Comment by fanvcz934n** [comment]
after send several times dm to others，account was suspended。

**Comment by d60** [comment]
@fanvcz934n 
https://github.com/d60/twikit/blob/main/ToProtectYourAccount.md#do-not-send-too-many-messages

**Comment by zhangzyg** [comment]
@fanvcz934n 
do we have a functionality that can search from some time range? as maximum is 20, I seed get all data from some time range, then I must request serveral times

**Comment by zhangzyg** [comment]
@fanvcz934n 
do we have a functionality that can search from some time range? as maximum is 20, I seed get all data from some time range, then I must request serveral times
