### ISSUE TITLE
Delete comments

### ISSUE THREAD

**Issue by Bits4Bux** [d60/twikit#160]
Is there a way to delete comments?

Thanks in advance

**Comment by d60** [comment]
@Bits4Bux 
To delete a comment, you can use the delete_tweet method. Here is an example of how to do it:

python
コードをコピーする
client.delete_tweet(tweet_id_here)

**Comment by d60** [comment]
@Bits4Bux 

you can use delete_tweet method to delete comments.

await client.delete_tweet(tweet id here)

**Comment by Bits4Bux** [comment]
It worked, thank you :)
