### ISSUE TITLE
status: 400, message: "{"errors":[{"code":398,"message":"Can't complete your signup right now."}]}"

### ISSUE THREAD

**Issue by dominic-m-silveira** [d60/twikit#163]
My code worked perfectly for many weeks...

But today I got the following error
```
status: 400, message: "{"errors":[{"code":398,"message":"Can't complete your signup right now."}]}"
```

Twitter has changed the login process?
Is anyone facing the same issue?

Thank you!

**Comment by d60** [comment]
@dominic-m-silveira 
You might have logged in too many times. try waiting for a while or using a different account.

**Comment by d60** [comment]
if you are logging in every time you run the program, try saving and loading cookies.
like this https://github.com/d60/twikit/blob/main/examples/dm_auto_reply.py#L15

**Comment by dominic-m-silveira** [comment]
Hi @d60 , I always use the save/load cookie method for Twikit. 
I got above error when I tried to log in with a newly created account on Twikit, because other accounts were ... 
I suspect that Twitter has placed a login limit on my IP.

I tried the below work around and it worked

Solution:
- Install EditThisCookie extension: https://chrome.google.com/webstore/detail/fngmhnnpilhplaeedifhccceomclgfbg
- Open twitter and click on EditThisCookie and click on export option to copy json and paste it in a file
- Convert cookie exported from EditThisCookie to Twikit cookie format =>
```
import json

with open('<path to EditThisCookie json>', 'r') as file:
    data = json.load(file)

result = {}
for item in data:
    name = item.get("name")
    value = item.get("value")
    if name and value:
        result[name] = value

with open('<path to store cookie in twikit json format>', 'w') as file:
    json.dump(result, file, indent=4)
```

Hope someone finds it helpful
Thank you so much
I am closing this issue!

**Comment by Jobdaneri** [comment]
need add captcha solver after LoginEnterAlternateIdentifierSubtask

**Comment by dominic248** [comment]
> need add captcha solver after LoginEnterAlternateIdentifierSubtask

Please refer my above solution of exporting cookie via EditThisCookie, it will work without adding captcha to Twikit

Captcha solver seems impossible
- Captcha was made to stop bots
- different / new questions
- requires OCR and in some questions object in question and answer are not same

**Comment by neckker** [comment]
> Hi [@d60](https://github.com/d60) , I always use the save/load cookie method for Twikit. I got above error when I tried to log in with a newly created account on Twikit, because other accounts were ... I suspect that Twitter has placed a login limit on my IP.
> 
> I tried the below work around and it worked
> 
> Solution:
> 
> * Install EditThisCookie extension: https://chrome.google.com/webstore/detail/fngmhnnpilhplaeedifhccceomclgfbg
> * Open twitter and click on EditThisCookie and click on export option to copy json and paste it in a file
> * Convert cookie exported from EditThisCookie to Twikit cookie format =>
> 
> ```
> import json
> 
> with open('<path to EditThisCookie json>', 'r') as file:
>     data = json.load(file)
> 
> result = {}
> for item in data:
>     name = item.get("name")
>     value = item.get("value")
>     if name and value:
>         result[name] = value
> 
> with open('<path to store cookie in twikit json format>', 'w') as file:
>     json.dump(result, file, indent=4)
> ```
> 
> Hope someone finds it helpful Thank you so much I am closing this issue!

How long do cookies hold data for? A week, a month?

**Comment by dominic248** [comment]
> How long do cookies hold data for? A week, a month?
Hi @neckker, cookie value gets saved back to the file using save cookie method
But if your account gets banned due to many requests, then the cookie values are useless
