### ISSUE TITLE
Does this library supports built queries?

### ISSUE THREAD

**Issue by umutbozdag** [d60/twikit#167]
I have look to the docs but I couldn't find it, does this library supports built queries like "abc OR xyz", like here: https://developer.x.com/en/docs/twitter-api/v1/rules-and-filtering/search-operators

**Comment by d60** [comment]
yes
client.search_tweet('abc OR xyz', 'Latest')

**Comment by umutbozdag** [comment]
That was so quick 😄, thanks buddy
