### ISSUE TITLE
Version 1.1.16 Added list

### ISSUE THREAD

**Issue by d60** [d60/twikit#18]
Hello! Version 1.1.16 has been released. The main updates in this version revolve around list-related functionalities.

Added:

`Client.create_list`: Creates a list.
`Client.edit_list_banner`: Modifies the banner image of a list.
`Client.delete_list_banner`: Deletes the banner of a list.
`Client.edit_list`: Edits the information of a list.
`Client.add_list_member`: Adds a member to a list.
`Client.remove_list_member`: Removes a member from a list.
`Client.get_list`: Retrieves a list from its ID.
`Client.get_list_tweets`: Retrieves tweets from a list.

`Client`: A class containing information and methods related to lists.

**Comment by HeIIow2** [comment]
Why don't you use the releases from github.

To do so you need to simply tagg a commit, and then you can upload builds e.g. `.whl` or `.tar.gz` or nothing to the release. GitHub then assosictes those files with the commit and additionaly uploads the source code.

You can also changelogs.
