### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by mightatnight** [d60/twikit#183]
twikit.errors.BadRequest: Status: 400, message: "{"errors":[{"code":366,"message":"flow name LoginFlow is currently not accessible"}]}" 2fa is on, but I gave the secret to the func

**Comment by d60** [comment]
@mightatnight #169

**Comment by mightatnight** [comment]
> @mightatnight #169 

Thank you, after setting the user agent it logs in. Should i install login fix in this case?

**Comment by d60** [comment]
You only need to install version 2.1.2.

**Comment by szsyzx** [comment]
> > @mightatnight #169
> 
> Thank you, after setting the user agent it logs in. Should i install login fix in this case?

请问您是怎么解决的
