### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by devilevil100** [d60/twikit#19]
Can there be a method to get image from dms. As of right now message.attachment does give a URL https://ton.twitter.com/1.1/ton/data/dm/etc  but it cant be used as cdn so need to extract one with cdn URL and for that need some auth I think

**Comment by d60** [comment]
Hello.
I found that I can get the image by setting the header and doing a get.
Please try it.

```python
attachment_url = 'https://ton.twitter.com/1.1/ton/data/dm/00000/00000/xxxxx.jpg'
response = client.http.get(
    attachment_url,
    headers=client._base_headers
)
image_binary = response.content
```
