### ISSUE TITLE
LoginFlow is currently not accessible

### ISSUE THREAD

**Issue by Gyanendra30** [d60/twikit#196]
I am using Twitter version 2.1.3 but when I try to login I am getting this error status: 400, message: "{"errors":[{"code":366,"message":"flow name LoginFlow is currently not accessible"}]}". Please suggest a solution. It is very important to solve this error.

i am using this code 

client_obj = Client(
        headers={
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
        }
    )

    time.sleep(5)

    await client_obj.login(
        auth_info_1=username.strip(),
        auth_info_2=email.strip(),
        password=password.strip(),
    )

    client_cookies = client_obj.get_cookies()

**Comment by consler** [comment]
Just had the same exact issue. It has already been solved multiple times by the way.
Add ` client = Client(user_agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36', language ='en-US)' ` before `async def main():`

**Comment by DemianOportus** [comment]
What about me? I am using the most basic example and it isn't working

`import asyncio

from twikit import Client

###########################################

# Enter your account information
USERNAME = XXXX
EMAIL = XXXX
PASSWORD = XXXX

client = Client('en-US')

async def main():
    # Asynchronous client methods are coroutines and
    # must be called using `await`.
    await client.login(
        auth_info_1=USERNAME,
        auth_info_2=EMAIL,
        password=PASSWORD
    )

asyncio.run(main())`

Same error, 

statsgetter/main.py", line 23, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/chris/Desktop/statsgetter/main.py", line 17, in main
    await client.login(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/twikit/client/client.py", line 400, in login
    await flow.execute_task({
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/twikit/utils.py", line 88, in execute_task
    response, _ = await self._client.v11.onboarding_task(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/twikit/client/v11.py", line 85, in onboarding_task
    return await self.base.post(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/twikit/client/client.py", line 190, in post
    return await self.request('POST', url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/twikit/client/client.py", line 164, in request
    raise BadRequest(message, headers=response.headers)
twikit.errors.BadRequest: status: 400, message: "{"errors":[{"code":366,"message":"flow name LoginFlow is currently not accessible"}]}"

**Comment by DemianOportus** [comment]
SOLVED THE ISSUE

<img width="489" alt="Screenshot 2024-08-31 at 10 10 54 PM" src="https://github.com/user-attachments/assets/e16b9935-db1d-4213-a99d-154848a4ba3f">

Log in with the desired account, check dev tools, go to NETWORK, and look for user-agent, as in the picture.

Copy paste that before your main async function and it will work!

Example code:

`import asyncio

from twikit import Client



### Enter your account information
USERNAME = 'XXXX'
EMAIL = 'XXXX'
PASSWORD = 'XXXX'

client = Client(
    user_agent='Mozilla/5.0 ................... (its very long haha)'
)

async def main():
    ## Asynchronous client methods are coroutines and
    ## must be called using await.
    await client.login(
        auth_info_1=USERNAME,
        auth_info_2=EMAIL,
        password=PASSWORD
    )
        ## Get user by screen name
    USER_SCREEN_NAME = 'elonmusk'
    user = await client.get_user_by_screen_name(USER_SCREEN_NAME)

    # Access user attributes
    print(
        f'id: {user.id}',
        f'name: {user.name}',
        f'followers: {user.followers_count}',
        f'tweets count: {user.statuses_count}',
        sep='\n'
    )


asyncio.run(main())`

**Comment by akmaldira** [comment]
```python
client = Client(
  user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36'
)

async def main():
    await client.login(
        auth_info_1=USERNAME ,
        auth_info_2=EMAIL,
        password=PASSWORD
    )
    client.save_cookies("cookies.json")

asyncio.run(main())
```

not working on me

**Comment by consler** [comment]
> ```python
> client = Client(
>   user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36'
> )
> 
> async def main():
>     await client.login(
>         auth_info_1=USERNAME ,
>         auth_info_2=EMAIL,
>         password=PASSWORD
>     )
>     client.save_cookies("cookies.json")
> 
> asyncio.run(main())
> ```
> 
> not working on me



That's kind of weird. It also does not work for me sometimes. The fix was just waiting a few minutes and trying again. I have no idea what causes that.

**Comment by johntdavies** [comment]
This worked for me, I used the same user_agent as a recent login from Chrome.

    client = Client(user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36')
    if os.path.exists(cookie_file):
        client.load_cookies(cookie_file)
    else:
        await client.login(
            auth_info_1=username,
            auth_info_2=email,
            password=password
        )
        client.save_cookies(cookie_file)

**Comment by yujingr** [comment]
using the user agent works, but when i switched to another computer, i had to logout and login on the new PC for the new pc's agent to work.

**Comment by Atlantropaz** [comment]
Tried a bunch of times via finding the user_agent in network. Still doesn't work on my end.

**Comment by arashmpr** [comment]
I did a weird fix and I don't understand exactly why it worked, but you can try see if works for you as well.

My code was very similar to you:

```
config = ConfigParser()
config.read('config.ini')
username = config['X']['username']
password = config['X']['password']
email = config['X']['email']

async def login():
    client = Client(language='en-US')
    try:
        await client.login(auth_info_1=username, auth_info_2=email, password=password)
        client.save_cookies('cookies.json')
    except Exception as e:
        logging.error(f"An error occurred: {e}")
        raise
```

but then I substitute `username`, `email` and `password` variable with the actual strings and it worked. I don't know why because I just copied from my config.ini, therefore, my config details were valid. 

So let's say if in my configs my username, email and password were these values:

```
username = '1234'
password = 'pass1234'
email = '1234@gmail.com'
```

then your code should be like this:

```
async def login():
    client = Client(language='en-US')
    try:
        await client.login(auth_info_1='1234', auth_info_2='1234@gmail.com', password='pass1234')
        client.save_cookies('cookies.json')
    except Exception as e:
        logging.error(f"An error occurred: {e}")
        raise
```

I hope this helps.

**Comment by hosamn** [comment]
> SOLVED THE ISSUE
> <img alt="Screenshot 2024-08-31 at 10 10 54 PM" width="489" src="https://private-user-images.githubusercontent.com/90730285/363452789-e16b9935-db1d-4213-a99d-154848a4ba3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4OTQ3MTAsIm5iZiI6MTczNjg5NDQxMCwicGF0aCI6Ii85MDczMDI4NS8zNjM0NTI3ODktZTE2Yjk5MzUtZGIxZC00MjEzLWE5OWQtMTU0ODQ4YTRiYTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE0VDIyNDAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3OWZiNmQ3NmIyNDEzNzYyN2M5OTg4MjQ0YzQ0ZjY3ZmQ3ZGU1MjViM2JlNzg3NWM2MjQwYjBkY2U1NmM2NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3sbdHNoNdWw62q3t4IaptDlRsiYBBBLVOe0lJvRw8Ug">
> 
> Log in with the desired account, check dev tools, go to NETWORK, and look for user-agent, as in the picture.
> 
> Copy paste that before your main async function and it will work!
> 
> Example code:
> 
> `import asyncio
> 
> from twikit import Client
> ### Enter your account information
> 
> USERNAME = 'XXXX' EMAIL = 'XXXX' PASSWORD = 'XXXX'
> 
> client = Client( user_agent='Mozilla/5.0 ................... (its very long haha)' )
> 
> async def main(): ## Asynchronous client methods are coroutines and ## must be called using await. await client.login( auth_info_1=USERNAME, auth_info_2=EMAIL, password=PASSWORD ) ## Get user by screen name USER_SCREEN_NAME = 'elonmusk' user = await client.get_user_by_screen_name(USER_SCREEN_NAME)
> 
> ```
> # Access user attributes
> print(
>     f'id: {user.id}',
>     f'name: {user.name}',
>     f'followers: {user.followers_count}',
>     f'tweets count: {user.statuses_count}',
>     sep='\n'
> )
> ```
> 
> asyncio.run(main())`





Ran that and got this:

```
TypeError: Client.__init__() got an unexpected keyword argument 'user_agent'
```
