### ISSUE TITLE
next() returning same tweets each time

### ISSUE THREAD

**Issue by tarltarasa** [d60/twikit#197]
I am trying to use the following example from examples.py:
```
    # Get user tweets
    user_tweets = await user.get_tweets('Tweets')
    for tweet in user_tweets:
        print(tweet)
    # Get more tweets
    more_user_tweets = await user_tweets.next()
```
However, what I am finding is that each subsequent time I call next() it's giving me the same set of tweets again. How do I make it move on to the next set of tweets?

**Comment by CatBraaain** [comment]
you can try this as below
https://github.com/d60/twikit/issues/131#issuecomment-2261838355

**Comment by tarltarasa** [comment]
Ah, perfect! Thanks very much!
