### ISSUE TITLE
BadRequest: status: 400, message: "{"errors":[{"code":366,"message":"flow name LoginFlow is currently not accessible"}]}"

### ISSUE THREAD

**Issue by Saul-Github** [d60/twikit#199]
After trying the method of using user-agent, I still got this error.

Here are the codes:

import asyncio
from twikit import Client

USERNAME = 'XXX'
EMAIL = 'XXX'
PASSWORD = XXX'

client = Client(user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) ...')

async def main():
    await client.login(
        auth_info_1=USERNAME,
        auth_info_2=EMAIL,
        password=PASSWORD
    )

asyncio.run(main())

Any suggestions, thank you!

**Comment by otterolie** [comment]
Change the user agent to something else:

ie

client = Client(
    user_agent="Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15A372 Safari/604.1"
)

**Comment by DemianOportus** [comment]
[Here](https://github.com/d60/twikit/issues/196#issuecomment-2323123750) is my solution:

**Comment by bethylamine** [comment]
From the Discord community announcement channel:

> d60 — 08/23/2024 8:14 AM
> Version 2.1.3
> * Fixed `KeyError: 'open_account'"`
> * `flow name LoginFlow is currently not accessible` has not yet been fixed.

So this is a known issue being worked on.

**Comment by mbfczzz** [comment]
I had the same problem last night, but I fixed the user agent and it was fine.

**Comment by 0n7** [comment]
up

**Comment by EyalShechtman** [comment]
> I had the same problem last night, but I fixed the user agent and it was fine.

so what did you do to fix it?

**Comment by d60** [comment]
try version 2.2.0
