### ISSUE TITLE
Reading bookmarks

### ISSUE THREAD

**Issue by nikitavoloboev** [d60/twikit#2]
Allow exporting/searching of bookmarks.

**Comment by d60** [comment]
Thank you for your feedback! I will start working on exporting bookmarks and implementing the search function today. Please wait a while.

**Comment by nikitavoloboev** [comment]
If you could add as metadata the folder in which the bookmark is, would be amazing.

Also deleting bookmarks would be great too.

So that you could export say, 10 latest bookmarks and then delete them from Twitter.

**Comment by nikitavoloboev** [comment]
Can try contribute to this as I really need this feature. Either financially or with code. 🖤

**Comment by d60** [comment]
Got it. I plan to add features for retrieving and deleting bookmarks. Additionally, I intend to introduce a new Bookmark class. Thank you for your suggestions🖤

**Comment by d60** [comment]
**version 1.1.4**

Hello. I have added the `get_bookmarks` method as planned.
A simple example:
```python
bookmarks = client.get_bookmarks()
print(bookmarks)
# [<Tweet id="...">, <Tweet id="...">, ..., <Tweet id="...">]

more_bookmarks = bookmarks.next()
print(more_bookmarks)
# [<Tweet id="...">, <Tweet id="...">, ..., <Tweet id="...">]
```

I also added a `delete_all_bookmarks` method.
It can clear all bookmarks for the current account.

**Comment by nikitavoloboev** [comment]
Thank you a lot. 

I will try this in a bit. Does this carry a risk of having my account banned too if I use `client.get_bookmarks()` when I have a lot of bookmarks?

I am a bit confused how to get the use case of grab me 10 latest bookmarks. What would that look in code? Also so that bookmark has the metadata of the folder it is in if it's in a folder.

Also `delete_all_bookmarks` is neat but I'd love to similar to above case, do `deleteRecentBookmarks(number: int)` kind of api. 

Hope that makes sense.

**Comment by d60** [comment]
Hello.
①The get_bookmarks method does not retrieve all bookmarks, but only some. So your account will not be banned in a single run.
② To get 10 bookmarks, set the second argument of the method, `count`, to 10.
③ I will add the folder metadata later.
④ To retrieve recent bookmarks do the following:
```python
bookmarks = client.get_bookmarks(count=10)
for bookmark in bookmarks:
    bookmark.delete_bookmark()
```
