### ISSUE TITLE
twikit.errors.BadRequest: status: 400, message: "{"errors":[{"code":366,"message":"flow name LoginFlow is currently not accessible"}]}"

### ISSUE THREAD

**Issue by Carsoncantcode** [d60/twikit#221]
twikit.errors.BadRequest: status: 400, message: "{"errors":[{"code":366,"message":"flow name LoginFlow is currently not accessible"}]}"

I get this error when trying to get my cookies

**Comment by d60** [comment]
Duplicate of #169
