### ISSUE TITLE
Flow name LoginFlow is currently not accessible. 

### ISSUE THREAD

**Issue by lichao23** [d60/twikit#236]
“Flow name LoginFlow is currently not accessible.”

I encountered the same issue. There are two servers—one works fine, but the other always throws this error no matter what. Both environments are identical Docker setups, and Java calls a Python script. I’ve also tried changing the user-agent multiple times, but it didn’t help.

The `Client` is created at the start of the script, and it’s used within the method.

I’ve tried most of the solutions related to this issue from the list, but I still can’t figure out what the problem is.

My final workaround was to log in on the test server, obtain the cookie, and then use it on the production server to bypass the login step. But how long can this solution last?

**Comment by desktop69** [comment]
Hi, I’m working on a similar setup and also encountered the "Flow name LoginFlow is currently not accessible" issue. I'm trying to use manual cookies to bypass login, but I couldn’t locate the _twitter_sess cookie in Chrome DevTools or other export methods. Could you explain how you managed to obtain _twitter_sess or if you use another combination of cookies (like auth_token) to maintain the session? Any help would be appreciated!

**Comment by SheebSuka** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by d60** [comment]
v2.2.0
