### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by brownepres** [d60/twikit#250]
When I try to log in with my login credentials I receive a list index out of range error. I understand that 90% of the time this is an error from my side, however I was able to log in with the exact lines of code just a couple days ago. 

I use the login code provided here except I run main() with await instead of asyncio in pyhton.

Anyone got any ideas what might be wrong?

**Comment by nitayStain** [comment]
did you handle it yet?

**Comment by brownepres** [comment]
> did you handle it yet?

Yes, I figured out after a few days that I had two different python versions running on normal python and on anaconda environment, and only the latter worked properly.
