### ISSUE TITLE
Help Needed: Twikit send_dm 404 Error – {"message":"Sorry, that page does not exist","code":34}

### ISSUE THREAD

**Issue by desktop69** [d60/twikit#259]
Hi everyone,

I’ve been using the Twikit library to build a messaging bot, and it was working perfectly for a while. Recently, however, I’ve started encountering the following error when trying to send a direct message (DM):

> Unexpected error: status: 404, message: "{"errors":[{"message":"Sorry, that page does not exist","code":34}]}"

**The Code Context**
Here’s the relevant portion of my code:

```
import asyncio
import json
from twikit import Client
# Initialize client
client = Client(language='en-US')
async def main():
    cookies_file = 'cookies.json'
    # Load cookies
    with open(cookies_file, 'r', encoding='utf-8') as f:
        client.set_cookies(json.load(f))

    user = await client.get_user_by_screen_name("userfortesting")

    try:
        # Attempt to send the DM
        await client.send_dm(user.id, "yow yow")
        print(f"Successfully sent DM to user {user.id}")
    except Exception as e:
        print(f"Unexpected error: {str(e)}")

    print("done!")

asyncio.run(main())
```
It seems like the send_dm function is no longer able to find the endpoint. Based on the error message ("Sorry, that page does not exist"), I suspect that Twitter/X might have changed the API endpoint for sending DMs.
Important Note

Interestingly, this same issue occurred two days ago but resolved itself automatically after about 5 hours without any changes on my side. This makes me wonder if the problem could be related to temporary server-side issues or rate limits on Twitter/X’s end.
**Questions for the Community**

Has anyone else experienced this issue recently?
If so, were you able to resolve it or identify the root cause?
Could this be due to a change in Twitter/X’s API?
I’ve checked the Twitter Developer documentation but haven’t found any obvious announcements about DM-related updates.
Are there tools or methods to discover the new API endpoint?
I’m considering using tools like Charles Proxy or browser DevTools to track the network calls made by Twitter/X’s web app. Does anyone have recommendations or a better approach for this?
**Suggestions for Updating Twikit**
If the endpoint has changed, what’s the best way to patch the send_dm function? I’m open to modifying the library temporarily until an official fix is released.

**Any Help Is Appreciated!**

If you’ve faced a similar issue or have insights into debugging or fixing this, I’d love to hear from you. This is an urgent matter for my project, and any advice or pointers would be greatly appreciated.

Thanks in advance for your help! 😊

**Comment by d60** [comment]
try version 2.2.0

**Comment by desktop69** [comment]
> try version 2.2.0

alright thank you, keep up the good work man

**Comment by Cryptojoyz** [comment]
> try version 2.2.0

I still met this problem in `await client.user_id()` . I have updated to 2.2.0

**Comment by Kolaposki** [comment]
I'm getting this problem as of now. I am using version  2.2.1

Does anyone know a way around this?
