### ISSUE TITLE
How to get the url of a tweet itself? 

### ISSUE THREAD

**Issue by vegetabo** [d60/twikit#262]
I print all attributes of Tweet, but there is no URL for itself.

**Comment by cmj** [comment]
If you want the url, you just need the `rest_id` for each conversation/tweet. The shortUrl method is `https://x.com/_/status/$id`

**Comment by mrienstra** [comment]
Alternate URL format, this one avoids a redirect:
```js
`https://x.com/i/web/status/${tweet_id}`
```

([source](https://stackoverflow.com/questions/27836043/get-tweet-url-having-only-tweet-id#58680337))
