### ISSUE TITLE
failing to get a post replies

### ISSUE THREAD

**Issue by gitgetgotguts** [d60/twikit#269]
is there a way to load twikit cookies into selenium that would be helpful to login

**Comment by gitgetgotguts** [comment]
I've created a  script that can get repliers with selenium you can find it in my  profile

**Comment by cmj** [comment]
By the way, here's a short example on how to retrieve replies using twikit itself instead of using Selenium:\
https://github.com/cmj/twitter-tools/blob/main/twikit-replies.py

This file notes what other attributes can be extracted:\
https://github.com/d60/twikit/blob/main/twikit/tweet.py#L18-L89

**Comment by gitgetgotguts** [comment]
yes I saw this but it's not accurate it dosent get all the replies so I had to use selenium because I only needed the repliers id
