### ISSUE TITLE
notify types to Python static analyzer

### ISSUE THREAD

**Issue by shunsock** [d60/twikit#28]
Hi, there. I want to use this library with static analyzer such as mypy or something else.

notifying type to static analyzer, I suppose use following method

1. adding py.dyped in `./twikit`
we just put empty file.

2. adding section `package_data` to setup function parameter.

```python
import re

from setuptools import setup

with open('README.md', encoding='utf-8') as f:
    long_description = f.read()

with open('./twikit/__init__.py') as f:
    version = re.findall(r"__version__ = '(.+)'", f.read())[0]

setup(
    name='twikit',
    version=version,
    install_requires=['httpx', 'fake_useragent'],
    package_data={'twikit': ['py.typed']},                                                              # Add this line
    description='Twitter API wrapper for python with **no API key required**.',
    long_description=long_description,
    long_description_content_type='text/markdown',
    license='MIT',
    url='https://github.com/d60/twikit'
)
```

This is reference. Need more information, please look following url.
https://peps.python.org/pep-0561/

I hope the project continues to grow.
Thank you for reading.

**Comment by ShoGinn** [comment]
I don't think this was correctly implemented because `mypy` still complains.

Rather than figure out how to set it up, can you add the `py.typed` file to the module directory?

Thanks!
