### ISSUE TITLE
Returning all posts made by me

### ISSUE THREAD

**Issue by nikitavoloboev** [d60/twikit#4]
Similar to https://github.com/d60/twikit/issues/2 and https://github.com/d60/twikit/issues/3 I want to be able to return all the posts/replies made by me either across all time or in some interval (i.e. last 7 days). Perhaps it's possible already.

**Comment by d60** [comment]
Do you mean you want to retrieve all the replies and tweets you have made?

**Comment by nikitavoloboev** [comment]
Correct.

**Comment by d60** [comment]
Ok, I understand. Try this.
```python
all_tweets = []

tweets = client.get_user_tweets('your user id', 'Replies')

while len(tweets) == 0:
    all_tweets += list(tweets)
    tweets = tweets.next()

print(all_tweets)
```

However, please note that too many requests to the API may result in the account being banned.
