### ISSUE TITLE
Accidental PR reversion?

### ISSUE THREAD

**Issue by GormanFletcher** [d60/twikit#40]
It looks like commit [8c9e8e2](https://github.com/d60/twikit/commit/8c9e8e22efaf3a78e7e3883f6cc71e29fd7b5643) uploaded an older version of the code that undid everything from #35 and #39?

**Comment by d60** [comment]
A bug was found in the get_user_tweets function, so as a temporary measure, the code was reverted. Plans are in place to update it once the bug is fixed. I expect to have it done by next week.

**Comment by GormanFletcher** [comment]
Not sure what bug you hit but I do have some more commits on my fork fixing issues with deleted/restricted-access tweets, especially in quote tweets.
