### ISSUE TITLE
Some tweets retrieved with get_tweet_by_id give list index out of range error 

### ISSUE THREAD

**Issue by paquirodeniro2** [d60/twikit#41]
As explained in the title there are tweets for which i dont know why the result for the function get_tweet_by id  is list index out of range. If I check other tweet the result is correct, so i do not think the account is at fault.

EXEMPLE CODE OF THIS PROBLEM:

try:
        print("We try a tweet with id: 1764666449073758266")
        tweet = client.get_tweet_by_id("1764666449073758266")
        print(tweet)
        # Access tweet attributes
        print(
        f'id: {tweet.id}',
        f'text {tweet.text}',
        sep='\n'
        )
except:
        print("It failed, we try another tweet, with id 1764666472948011274")
        tweet = client.get_tweet_by_id("1764666472948011274")
        print(tweet)
        # Access tweet attributes
        print(
        f'id: {tweet.id}',
        f'text {tweet.text}',
        sep='\n'
        )

**Comment by d60** [comment]
Fixed
