### ISSUE TITLE
user.get_tweets('Tweets', count=10) At issue

### ISSUE THREAD

**Issue by anxiaochuang** [d60/twikit#49]
I'm not sure if it's a problem with my code, here's my code:
tweets = await user.get_tweets('Tweets', count=10)
for tweet in tweets:
print(tweet.id)
print('====================')
The number printed is greater than 10, and the data obtained is incomplete (the latest tweet cannot be obtained)

**Comment by diegoasua** [comment]
Same

**Comment by d60** [comment]
Due to a bug in the Twitter API, specifying a count does not currently limit the number of results returned, but always returns the maximum number of results. Therefore, use list slicing to get only the required number of results.
