### ISSUE TITLE
.

### ISSUE THREAD

**Issue by emircandogan1** [d60/twikit#55]
.

**Comment by d60** [comment]
@emircandogan1 
You can do that simply by including a hashtag in the search query.

Example:
```python
tweets = client.search_tweet('#python')
```

**Comment by emircandogan1** [comment]
user = client.search_tweet('#elon', 'Latest')
tweets = user.get_tweets('Tweets', count=5)

after run this i got error:
AttributeError: 'Result' object has no attribute 'get_tweets'

**Comment by emircandogan1** [comment]
i solved this problem with without using: 

tweets = user.get_tweets('Tweets', count=5) # we don't need that, search_tweet returns tweet.
