### ISSUE TITLE
The get_tweets() method does not respect the count

### ISSUE THREAD

**Issue by Plaoo** [d60/twikit#66]
Using the get_tweets method I realized that the tweets count is not respected, by default it is 40, if I don't set it I see only 20 urls of tweets (urls retrieved from the data I get with the get_tweets("Media") method).

**Comment by Plaoo** [comment]
Found the problem

**Comment by roadrage312** [comment]
what was the problem? I have the same issue. Want to retrieve only last 5

**Comment by einarjohnson** [comment]
also seeing this error, i set count=1 but I receive much more.

**Comment by superclarkk** [comment]
@Plaoo Others are facing this issue. What was your problem?
