### ISSUE TITLE
get_user_tweets with tweet_type="Replies" seems to not work properly

### ISSUE THREAD

**Issue by multiplegamer9** [d60/twikit#67]
![imagen](https://github.com/d60/twikit/assets/66864565/34725baf-f1fa-4766-bb6e-c4a2a024c064)
these are the .in_reply_to 's of the get_user_tweets(tweet_type="Replies") of user @d1mden on twitter as of writing this (just an example)
-

![SRoMJ18](https://github.com/d60/twikit/assets/66864565/434ff023-f5d9-4122-886e-1b2a033ec327)
### and here is the reply page, as you can see there are a lot of replies by d1mden as of writing this, but none of them seem to be getting successfully fetched by twikit despite having "Replies" on

**Comment by Kimononono** [comment]
If you haven't found it yet, 
tweet_obj._data['legacy'] gives you an incomplete version of the replied to tweet
tweet_obj._data['legacy']['id_str'] gives you the id

It was helpful inspecting tweet_obj.__dict__. Seems the variables defined in the Tweet class are extracted from _data for ease of top level access
