### ISSUE TITLE
How to get chat history of user or last X messages sent

### ISSUE THREAD

**Issue by nikitavoloboev** [d60/twikit#74]
I have chat with another user on X. I want API that returns either all or last 10/20 messages I have with that user. 

Thank you. ♥️

**Comment by d60** [comment]
@nikitavoloboev You can use ` Client.get_dm_history` to retrieve messages.
```python
messages = client.get_dm_history('1234567')
print(messages)
#> [<Message id="...">, <Message id="...">, ..., <Message id="...">]

#  Retrieve more messages
more_messages = messages.next()
```
