### ISSUE TITLE
How post rate limit works?

### ISSUE THREAD

**Issue by itsManeka** [d60/twikit#81]
How post rate limit works?
The documentation doesn't have a number limit.
How many posts I can do without receive 429 error?
How many time I need wait to retry?

Sometimes 1 hour works and sometimes not.

Is necessary login again after 429? Cookies will work after this?

**Comment by d60** [comment]
https://github.com/d60/twikit/blob/main/ratelimits.md
Not necessary to log in again

**Comment by itsManeka** [comment]
Firstly, thanks for the response! But, as I said above, I had already read this documentation. There is no limitation information about the rate limit for creating tweets, but in practice it is occurring.

After the ratelimit occurs, it doesn't work again for days. If you log in again, you will be released.

I'm running inside an aws instance. I also saw somewhere an indication about using a proxy in AWS, but when using it the problem seems to persist.

Another question: Is there any way to keep the data from the previous cookie device when you need to log in again and thus avoid the new device message on the account?
