### ISSUE TITLE
forbidden 403

### ISSUE THREAD

**Issue by Ellinach** [d60/twikit#87]
It gives me this error when i tried to retrieve data from twitter '
"bidden                                 Traceback (most recent call last)
Cell In[20], line 1
----> 1 tweets = scraper.get_user_tweets('usa','Tweets')
      2 tweets

File ~\anaconda3\Anacond\New folder\Lib\site-packages\twikit\client.py:1761, in Client.get_user_tweets(self, user_id, tweet_type, count, cursor)
   1750 params = flatten_params({
   1751     'variables': variables,
   1752     'features': FEATURES
   1753 })
   1754 endpoint = {
   1755     'Tweets': Endpoint.USER_TWEETS,
   1756     'Replies': Endpoint.USER_TWEETS_AND_REPLIES,
   1757     'Media': Endpoint.USER_MEDIA,
   1758     'Likes': Endpoint.USER_LIKES,
   1759 }[tweet_type]
-> 1761 response = self.http.get(
   1762     endpoint,
   1763     params=params,
   1764     headers=self._base_headers
   1765 ).json()
   1767 instructions_ = find_dict(response, 'instructions')
   1768 if not instructions_:

File ~\anaconda3\Anacond\New folder\Lib\site-packages\twikit\http.py:51, in HTTPClient.get(self, url, **kwargs)
     50 def get(self, url, **kwargs) -> httpx.Response:
---> 51     return self.request('GET', url, **kwargs)

File ~\anaconda3\Anacond\New folder\Lib\site-packages\twikit\http.py:36, in HTTPClient.request(self, method, url, **kwargs)
     34     raise Unauthorized(message, headers=response.headers)
     35 elif status_code == 403:
---> 36     raise Forbidden(message, headers=response.headers)
     37 elif status_code == 404:
     38     raise NotFound(message, headers=response.headers)

Forbidden: status: 403, message: ""

**Comment by d60** [comment]
@Ellinach 
That error means that the client is not authorised. Are you logged in to your account?

**Comment by hxbylishenfan** [comment]
sure,i can logged in browser normally.but i suspect it is an issue with overseas agants
