### ISSUE TITLE
Counts Not Respected When Retrieving Tweets

### ISSUE THREAD

**Issue by 0xVeta** [d60/twikit#90]
When using ```client.get_user_tweets``` or ```user.get_tweets```, the counts I set are not being respected. Regardless of what number is set, the number of tweets returned is unchanged.

In previous Issues I've seen that this is potentially an issue with the Twitter API. Is that still the case? Is there a way to return more tweets than the default amount?

**Comment by d60** [comment]
@0xVeta 
No, it is not possible to get more results than the default amount. Instead, use next method to fetch more results.
