### ISSUE TITLE
Fetching posts

### ISSUE THREAD

**Issue by Epikcoder** [d60/twikit#95]
is it possible to fetch al posts, not 20?
for example: amexoffers profile have  7,628,024  posts according to https://www.trackalytics.com/twitter/profile/amexoffers/

but when tried fetching it using
    tweets = client.get_user_tweets(code, 'Tweets')
    print(len(tweets))

I got 20 posts
![image](https://github.com/d60/twikit/assets/104178698/b23e5d1b-7d79-4a11-805c-e742eac41b0a)

**Comment by d60** [comment]
@Epikcoder 

You can retrieve more tweets using the 'next' method.
```python
tweets = client.get_user_tweets(code, 'Tweets')
more_tweets = tweets.next()
```
However it would be impossible to retrieve all 7,628,024 tweets due to factors such as rate limits.
